#!/bin/bash
set -e

#**********************************************************************************
# User configurable part
DISK=/dev/sda
KEYMAP="hu"
SWAPSIZE="2G"

USERNAME="arch"     # the password is "arch"
#**********************************************************************************

clear
echo "----------------------------------------------------------------------------------------------------"
echo " [1/2] Arch linux setup script"
echo "----------------------------------------------------------------------------------------------------"
CHOISE="no"
read -n1 -r -p "continue? [y/n]" CHOISE
CHOISE=${CHOISE,,} #to lovercase
if [ $CHOISE != "y" ] && [ $CHOISE != "yes" ] && [ $CHOISE != "" ];
then
    exit 1
fi
echo ""


# partitioning
(
    echo n; echo p; echo 1; echo ""; echo +$SWAPSIZE; # creating swap
    echo n; echo p; echo 2; echo ""; echo "";  # creating main filesystem

    echo t; echo 1; echo 19; # (TODO) this needs to be swap, may change
    
    echo w
) | fdisk $DISK
mkswap "${DISK}1"
swapon "${DISK}1"

mkfs.ext4 "${DISK}2"
mount "${DISK}2" /mnt

pacman -Sy
pacstrap /mnt base linux linux-firmware

genfstab -U /mnt >> /mnt/etc/fstab


cat << EOF | arch-chroot /mnt
echo $USERNAME | sudo tee /etc/hostname
echo "127.0.0.1      localhost
::1      localhost
127.0.1.1      $USERNAME.localdomain      $USERNAME"


echo -e "arch\narch" | passwd
useradd -m $USERNAME
echo -e "arch\narch" | passwd $USERNAME
usermod -aG wheel,audio,video $USERNAME
echo "Done setting up users"


pacman -S --noconfirm sudo
echo "%wheel ALL=(ALL:ALL) ALL" | sudo EDITOR="tee -a" visudo

pacman -S --noconfirm networkmanager
systemctl enable NetworkManager

pacman -S --noconfirm grub
grub-install --target=i386-pc $DISK
grub-mkconfig -o /boot/grub/grub.cfg
EOF


umount -R /mnt

clear
echo "----------------------------------------------------------------------------------------------------"
echo " Done installation script"
echo " Remove the installation medium and reboot"
echo " After reboot, run the after_setup script"
echo "----------------------------------------------------------------------------------------------------"