#!/bin/bash

#**********************************************************************************
# User configurable part
DISK=/dev/sda
KEYMAP="hu"
SWAPSIZE="2G"

USERNAME="arch"     # the password is "arch"
#**********************************************************************************

clear
set -e


echo "----------------------------------------------------------------------------------------------------"
echo " Arch linux setup script"
echo "----------------------------------------------------------------------------------------------------"
read -n1 -r -p "continue? [y/n]" choice
choice=${choice,,} #to lovercase
if [ $choice != "y" ] && [ $choice != "yes" ] && [ $choice != "" ];
then
    echo "Continuing..."
else
    exit 0
fi

#localization, change for your language
loadkeys $KEYMAP
/etc/locale.conf >> LANG=en_US.UTF-8
/etc/vconsole.conf >> KEYMAP=$KEYMAP

timedatectl set-ntp true

# partitioning
# (sda)
(
    echo n; echo p; echo 1; echo ""; echo +$SWAPSIZE; # creating swap
    echo n; echo p; echo 2; echo ""; echo "";  # creating main filesystem

    echo t; echo 1; echo 19; # (TODO) this needs to be swap, may change
    
    echo w
) | fdisk $DISK
mkswap "${DISK}1"
swapon "${DISK}1"

mkfs.ext4 "${DISK}2"
mount "${DISK}2" /mnt

pacstrap /mnt base linux linux-firmware

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt << "EOT"

EOT